#!/bin/bash

#tag::basic[]
# 服务端 nginx 静态资源目录
remoteDir="/usr/share/nginx/html"
# 删除历史文件
rm -rf build build.tar
# 重新构建
npm run build
# 打包
tar -cf build.tar build
# 部署到远程服务
scp build.tar "root@aliyun:$remoteDir"
ssh root@aliyun "cd $remoteDir; tar -xf build.tar; rm -rf bee; mv build bee"
# 打开浏览器
open -a "Google Chrome" "http://bee.peacetrue.cn"
#end::basic[]
