# Spring Boot Admin 配置

management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'

---
spring.config.activate.on-profile: dev

spring:
    boot:
        admin:
            client:
                url: ${BEE_MONITOR_URL_DEV}
                instance:
                    service-base-url: ${BEE_MAIN_URL_DEV}

---
spring.config.activate.on-profile: local

spring:
    boot:
        admin:
            client:
                url: ${BEE_MONITOR_URL_LOCAL}
                instance:
                    service-base-url: ${BEE_MAIN_URL_LOCAL}


---
spring.config.activate.on-profile: prod

spring:
    boot:
        admin:
            client:
                url: ${BEE_MONITOR_URL_PROD}
                instance:
                    service-base-url: ${BEE_MAIN_URL_PROD}
