#!/bin/bash

export BEE_VERSION=1.0.0

export BEE_FRONTEND_PORT=3000
export BEE_MAIN_PORT=${BEE_MAIN_PORT-8080}
export BEE_MONITOR_PORT=${BEE_MONITOR_PORT-8081}

export BEE_URL_DEV=http://localhost
export BEE_HOST_LOCAL=${BEE_HOST_LOCAL-bee.peacetrue.local}
export BEE_URL_LOCAL=http://$BEE_HOST_LOCAL
export BEE_HOST_PROD=${BEE_HOST_PROD-bee.peacetrue.cn}
export BEE_URL_PROD=http://$BEE_HOST_PROD

export BEE_FRONTEND_URL_DEV=$BEE_URL_DEV:$BEE_FRONTEND_PORT
export BEE_MAIN_URL_DEV=$BEE_URL_DEV:$BEE_MAIN_PORT
export BEE_MONITOR_URL_DEV=$BEE_URL_DEV:$BEE_MONITOR_PORT

export BEE_FRONTEND_URL_LOCAL=$BEE_URL_LOCAL
export BEE_MAIN_URL_LOCAL=$BEE_URL_LOCAL/api
export BEE_MONITOR_URL_LOCAL=$BEE_URL_LOCAL/monitor

export BEE_FRONTEND_URL_PROD=$BEE_URL_PROD
export BEE_MAIN_URL_PROD=$BEE_URL_PROD/api
export BEE_MONITOR_URL_PROD=$BEE_URL_PROD/monitor
