#!/bin/bash

set -x

cd "$(pwd)/.github/workflows" || exit
for app in FRONTEND MAIN MONITOR ; do
    for env in DEV LOCAL PROD ; do
      name="BEE_${app}_URL_${env}"
      value=$(printenv $name)
      sed -i "s|${name}.*|${name}: $value|g" macOS.yml
    done
done
