#!/bin/bash

set -u # 遇到不存在的变量就会报错，并停止执行
set -e # 脚本只要发生错误，就终止执行

ln -s $(pwd)/nginx/bee.peacetrue.local.conf $NGINX_CONFIG_DIR/bee.peacetrue.local.conf
ln -s $(pwd)/frontend/local $NGINX_HTML_DIR/html/bee
nginx -s reload
./macOS-dev-init
