#!/bin/bash

# 运行本地环境

pwd=$(pwd)
for app in main monitor; do
  cd "$pwd/backend/$app"
  #打包
  ./gradlew clean build
  remoteArchiveName="$app-boot-1.0.0"
  cd "build/distributions"
  tar -xf $remoteArchiveName.tar
  cd $remoteArchiveName
  nohup bin/$app >/dev/null 2>&1 &
done
