#!/bin/bash

# 运行本地环境

pwd=$(pwd)
for app in main monitor; do
  app="backend-$app"
  cd "$pwd/$app"
  #打包
  ./gradlew clean installBootDist
  cd "build/install/$app-boot"
  ps -ef | grep -i "Bee${app}Application" | grep -v grep | awk '{print $2}' | xargs kill -9
  nohup bin/$app >/dev/null 2>&1 &
done
