#!/bin/bash

# 初始化环境变量


# https://stackoverflow.com/questions/4990172/how-to-append-several-lines-of-text-in-a-file-using-a-shell-script
cat <<EOF >>~/.bashrc

export BEE_MAIN_PORT=8081
export BEE_MONITOR_PORT=8080
export BEE_MAIN_VERSION=1.0.0
export BEE_MONITOR_VERSION=1.0.0
export BEE_URL_DEV=http://localhost:$BEE_MAIN_PORT
export BEE_URL_LOCAL=http://bee.peacetrue.local
export BEE_URL_PROD=http://bee.peacetrue.cn

EOF

cat <<EOF >>~/.bashrc
export BEE_REMOTE_HOST=root@aliyun
export BEE_REMOTE_PASSWORD=123456
export BEE_REMOTE_PORT=
export BEE_REMOTE_MAIN_WORKING_DIR=~/bee/main
export BEE_REMOTE_MAIN_ARCHIVE_NAME=main-boot
EOF


source "$HOME/.bashrc"
