#!/bin/bash

# ubuntu 环境，初始化本地环境

# 在本机安装 Nginx
apt install nginx-core -y
export NGINX_CONFIG_DIR=/etc/nginx/conf.d
export NGINX_HTML_DIR=/usr/share/nginx/html

# Nginx 主配置文件 nginx.conf 中需导入扩展配置 include servers/*;
ln -s $(pwd)/nginx/bee.peacetrue.local.conf $NGINX_CONFIG_DIR/bee.peacetrue.local.conf
echo "127.0.0.1 $BEE_URL_DEV" >> /etc/hosts
ln -s $(pwd)/frontend/local $NGINX_HTML_DIR/bee

nginx -s reload
