#!/bin/bash

# ubuntu 环境，初始化生产环境

cat <<EOF >>~/.bashrc
export BEE_REMOTE_HOST=root@aliyun
export BEE_REMOTE_PASSWORD=123456
export BEE_REMOTE_PORT=
export BEE_REMOTE_MAIN_WORKING_DIR=~/bee/main
export BEE_REMOTE_MAIN_ARCHIVE_NAME=main-boot
EOF

source "$HOME/.bashrc"


# 安装 NGINX
# https://serverfault.com/questions/241588/how-to-automate-ssh-login-with-password
# https://stackoverflow.com/questions/32255660/how-to-install-sshpass-on-mac
sshpass -p $BEE_REMOTE_PASSWORD ssh $BEE_REMOTE_HOST <<EOF
apt install nginx-core -y
sed -i "s|www-data|root|g" /etc/nginx/nginx.conf
nginx -s reload
EOF

# 创建工作目录
sshpass -p $BEE_REMOTE_PASSWORD ssh $BEE_REMOTE_HOST "mkdir $BEE_REMOTE_WORKING_DIR; ln -s /usr/share/nginx/html $BEE_REMOTE_WORKING_DIR/html"

# 上传 bee.peacetrue.cn 配置
sshpass -p $BEE_REMOTE_PASSWORD scp "$(pwd)/nginx/bee.peacetrue.cn.conf" "$BEE_REMOTE_HOST:/etc/nginx/conf.d/bee.peacetrue.cn.conf"

