#!/bin/bash

# ubuntu 环境，运行本地环境

pwd=$(pwd)
for app in main monitor; do
cd "$pwd/backend/$app" || exit
# https://stackoverflow.com/questions/36923288/how-to-run-bootrun-with-spring-profile-via-gradle-task
nohup ./gradlew clean bootRun --args='--spring.profiles.active=local' >/dev/null 2>&1 &
done

