#!/bin/bash

# ubuntu 环境，初始化生产环境

apt install nginx-core -y
sed -i "s|www-data|root|g" /etc/nginx/nginx.conf
export NGINX_CONFIG_DIR=/etc/nginx/conf.d
export NGINX_HTML_DIR=/usr/share/nginx/html

tee $NGINX_CONFIG_DIR/bee.peacetrue.cn.conf <<EOF
server {
    listen       80;
    server_name  bee.peacetrue.cn;

    root html/bee;
    index index.html;

    location / {
        try_files \$uri \$uri/ /index.html;
    }

    location /monitor/ {
       proxy_pass http://localhost:$BEE_MONITOR_PORT/;
    }

    location /api/ {
       proxy_pass http://localhost:$BEE_MAIN_PORT/;
    }
}
EOF

nginx -s reload
