#!/bin/bash

# 部署后端

set -u # 遇到不存在的变量就会报错，并停止执行
#set -e # 脚本只要发生错误，就终止执行

pwd=$(pwd)
ssh $BEE_REMOTE_HOST "killall java"
for app in main monitor; do
  cd "$pwd/backend-$app"
  ./gradlew clean build
  remoteArchiveName="$app-boot-$BEE_VERSION"
  scp "build/distributions/$remoteArchiveName.tar" "$BEE_REMOTE_HOST:$BEE_REMOTE_WORKING_DIR"
  nohup ssh $BEE_REMOTE_HOST "cd $BEE_REMOTE_WORKING_DIR;rm -rf $remoteArchiveName;tar -xf $remoteArchiveName.tar;cd $remoteArchiveName;nohup bin/$app >/dev/null 2>&1 &"
done
