spring:
  profiles:
    group:
      default: dev
      dev: common,log-console
      local: common,log-file
      prod: common,log-file

---
spring.config.activate.on-profile: dev

spring:
  application:
    url: ${BEE_URL_DEV}

---
spring.config.activate.on-profile: local

spring:
  application:
    url: ${BEE_URL_LOCAL}

---
spring.config.activate.on-profile: prod

spring:
  application:
    url: ${BEE_URL_PROD}
