spring:
  profiles:
    group:
      default: dev
      dev: common,log-console
      local: common,log-file
      prod: common,log-file

---
spring.config.activate.on-profile: dev

spring:
  boot:
    admin:
      ui:
        # https://codecentric.github.io/spring-boot-admin/current/#_running_behind_a_front_end_proxy_server
        # 80 端口是必须的，否则会被替换为 server.port=8080
        public-url: ${BEE_MONITOR_URL_DEV}

---
spring.config.activate.on-profile: local

spring:
  boot:
    admin:
      ui:
        # https://codecentric.github.io/spring-boot-admin/current/#_running_behind_a_front_end_proxy_server
        # 80 端口是必须的，否则会被替换为 server.port=8080
        public-url: ${BEE_MONITOR_URL_LOCAL}

---
spring.config.activate.on-profile: prod

spring:
  boot:
    admin:
      ui:
        # https://codecentric.github.io/spring-boot-admin/current/#_running_behind_a_front_end_proxy_server
        # 80 端口是必须的，否则会被替换为 server.port=8080
        public-url: ${BEE_MONITOR_URL_PROD}
