= 前端项目
:module-name: frontend

优先实现功能，后续美化界面。

//@formatter:off

== 创建应用

参考 https://create-react-app.dev/docs/adding-typescript/ 。

[source%nowrap,bash,subs="specialchars,attributes"]
----
npx create-react-app {module-name} --template typescript

cd {module-name}
npm install
npm start
----

=== 更换图标

默认的 logo 图标为 React，需要替换为 Bee：

.logo.svg
[source%nowrap,xml]
----
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
    <path d="M21.94 4.88c-.18-.53-.69-.88-1.26-.88H19.6l-.31-.97C19.15 2.43 18.61 2 18 2s-1.15.43-1.29 1.04L16.4 4h-1.07c-.57 0-1.08.35-1.26.88-.19.56.04 1.17.56 1.48l.87.52-.4 1.24c-.23.58-.04 1.25.45 1.62.23.17.51.26.78.26.31 0 .61-.11.86-.32l.81-.7.81.7c.25.21.55.32.86.32.27 0 .55-.09.78-.26.5-.37.68-1.04.45-1.62l-.39-1.24.87-.52c.51-.31.74-.92.56-1.48zM18 7c-.55 0-1-.45-1-1s.45-1 1-1 1 .45 1 1-.45 1-1 1zm-4.51 3.51c-.43-.43-.94-.73-1.49-.93V8h-1v1.38c-.11-.01-.23-.03-.34-.03-1.02 0-2.05.39-2.83 1.17-.16.16-.3.34-.43.53L6 10.52c-1.56-.55-3.28.27-3.83 1.82-.27.75-.23 1.57.12 2.29.23.48.58.87 1 1.16-.38 1.35-.06 2.85 1 3.91s2.57 1.38 3.91 1c.29.42.68.77 1.16 1 .42.2.85.3 1.29.3.34 0 .68-.06 1.01-.17 1.56-.55 2.38-2.27 1.82-3.85l-.52-1.37c.18-.13.36-.27.53-.43.87-.87 1.24-2.04 1.14-3.17H16v-1h-1.59c-.19-.55-.49-1.06-.92-1.5zm-8.82 3.78c-.25-.09-.45-.27-.57-.51s-.13-.51-.04-.76c.19-.52.76-.79 1.26-.61l3.16 1.19c-1.15.6-2.63 1.11-3.81.69zm6.32 5.65c-.25.09-.52.08-.76-.04-.24-.11-.42-.32-.51-.57-.42-1.18.09-2.65.7-3.8l1.18 3.13c.18.52-.09 1.1-.61 1.28zm1.21-5.34-.61-1.61c0-.01-.01-.02-.02-.03l-.06-.12c-.02-.04-.04-.07-.07-.11l-.09-.09-.09-.09c-.03-.03-.07-.05-.11-.07-.04-.02-.07-.05-.12-.06-.01 0-.02-.01-.03-.02l-1.6-.6c.36-.29.79-.46 1.26-.46.53 0 1.04.21 1.41.59.73.73.77 1.88.13 2.67z"/>
</svg>
----

使用网站 https://cloudconvert.com/svg-to-ico[cloudconvert^]， 转换 logo.svg 为 favicon.ico 和 logo192.png、logo512.png。

== 实现布局

=== 布局设计

界面充满整个窗口，使用上中下布局：

* 上部为导航栏，高度固定，位置固定
* 中部为主体区域，高度自适应，填充窗口剩余高度
* 底部为页脚，高度固定，显示版权信息

=== 安装 MUI

参考 https://mui.com/zh/material-ui/getting-started/installation/ 。

.安装类库
[source%nowrap,bash,subs="specialchars,attributes"]
----
npm install @mui/material @mui/styled-engine-sc styled-components
npm install @mui/icons-material
----

参考 https://mui.com/zh/material-ui/react-typography/#general 。

.安装字体
[source%nowrap,bash,subs="specialchars,attributes"]
----
npm install @fontsource/roboto
----

.导入字体
[source%nowrap,js,subs="specialchars,attributes"]
----
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
----

roboto 字体和默认字体差别不大，如非必要无需使用。

=== 导航菜单

使用 https://mui.com/material-ui/react-tabs[Tabs^] 组件制作导航菜单。
首页时，导航菜单不选中；其他页面，导航菜单根据地址栏路径选中。

=== 路由跳转

路由使用浏览器模式：

.安装路由
[source%nowrap,bash,subs="specialchars,attributes"]
----
npm install react-router-dom@6
----

解决问题：

* https://stackoverflow.com/questions/63216730/can-you-use-material-ui-link-with-react-router-dom-link[MUI Link 和 router Link 配合使用^]
* https://juejin.cn/post/6844903942942359560[nginx 服务器配置 React 的 Browser 路由模式]

=== 功能主区域

点击功能菜单时，主区域会显示功能界面。

功能界面左侧为菜单，右侧为内容，通过路由实现跳转。

使用 https://mui.com/material-ui/react-tree-view[TreeView^] 组件制作功能菜单。
该组件是实验性的，需要安装扩展类库：

.lab
[source%nowrap,bash]
----
npm install @mui/lab
----

== 基础设施

工欲善其事，必先利其器。开发功能之前，准备好常用类库。

=== 工具

使用 https://github.com/lodash/lodash[lodash^] 作为工具类库， 安装命令如下：

.lodash
[source%nowrap,bash]
----
npm install lodash
----

=== 国际化

使用 https://github.com/i18next/react-i18next[react-i18next^] 支持国际化， 安装命令如下：

.react-i18next
[source%nowrap,bash]
----
npm install react-i18next i18next
----

使用 https://github.com/i18next/i18next-browser-languageDetector[i18next-browser-languageDetector^]
探测客户端语言， 安装命令如下：

.i18next-browser-languagedetector
[source%nowrap,bash]
----
npm install i18next-browser-languagedetector
----

=== 表单

使用 https://react-hook-form.com/[React Hook Form^] 处理表单， 安装命令如下：

.React Hook Form
[source%nowrap,bash]
----
npm install react-hook-form
----

使用 https://github.com/jquense/yup[yup^] 验证表单， 安装命令如下：

.yup
[source%nowrap,bash]
----
npm install yup
npm install @hookform/resolvers //<1>
----

<1> 配合 react-hook-form 使用

yup 默认提示英文，配合 react-i18next，自定义改造处理中文。

=== 请求

使用 https://github.com/axios/axios[axios^] 调用后端接口， 命令安装如下：

.axios
[source%nowrap,bash]
----
npm install axios
----

使用 https://github.com/ljharb/qs#stringifying[qs^] 格式化请求参数， 安装命令如下：

.qs
[source%nowrap,bash]
----
npm install qs
----

== 特性

* 主题切换（日 / 夜）
* 语言切换（中 / 英）
