name: macOS-local

on:
  push:
    branches: [ local ]
  workflow_dispatch:

permissions:
  contents: read

env:
  #  NGINX_CONFIG_DIR: /usr/local/etc/nginx/servers
  #  NGINX_HTML_DIR: /usr/local/Cellar/nginx/1.23.3
  BEE_MAIN_URL_LOCAL: http://bee.peacetrue.local/api
  BEE_URL_DEV: http://localhost
  BEE_MAIN_PORT: 8080
  BEE_FRONTEND_URL_PROD: http://bee.peacetrue.cn
  BEE_HOST_PROD: bee.peacetrue.cn
  BEE_FRONTEND_PORT: 3000
  BEE_MONITOR_URL_LOCAL: http://bee.peacetrue.local/monitor
  BEE_FRONTEND_URL_DEV: http://localhost:3000
  BEE_VERSION: 1.0.0
  BEE_MAIN_URL_PROD: http://bee.peacetrue.cn/api
  BEE_HOST_LOCAL: bee.peacetrue.local
  BEE_MAIN_URL_DEV: http://localhost:8080
  BEE_URL_LOCAL: http://bee.peacetrue.local
  BEE_FRONTEND_URL_LOCAL: http://bee.peacetrue.local
  BEE_MONITOR_URL_PROD: http://bee.peacetrue.cn/monitor
  BEE_MONITOR_PORT: 8081
  BEE_URL_PROD: http://bee.peacetrue.cn
  BEE_MONITOR_URL_DEV: http://localhost:8081
jobs:
  build:

    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: ./macOS-dev-init
      - run: ./macOS-dev-run-backend
      - run: ./macOS-dev-run-frontend
      - run: ./macOS-dev-test
        # https://brew.sh/
      - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - run: brew install nginx
      - run: killall java node
      #     https://stackoverflow.com/questions/66980682/is-it-possible-to-define-host-mappings-in-github-actions
      #     https://stackoverflow.com/questions/428109/extract-substring-in-bash
      - run: |
          sudo echo "127.0.0.1 ${BEE_HOST_LOCAL}" | sudo tee -a /etc/hosts
      - run: ./macOS-local-init
      - run: ./macOS-local-run-backend
      - run: ./macOS-local-run-frontend
      - run: ./macOS-local-test
