# 测试在 ubuntu 上运行 local 环境
name: macOS-local

on:
  push:
    branches: [ local ]
  workflow_dispatch:

permissions:
  contents: read

# 替代 set-env
env:
  BEE_MAIN_PORT: 8081
  BEE_MONITOR_PORT: 8080
  BEE_URL_DEV: "http://localhost:8081"
  BEE_URL_LOCAL: "http://bee.peacetrue.local"
  BEE_URL_PROD: "http://bee.peacetrue.cn"

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - run: ./macOS-dev-init
    - run: ./macOS-dev-run-backend
    - run: ./macOS-dev-run-frontend
      # https://brew.sh/
    - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - run: brew install nginx
    - run: nginx -v
    - run: killall java node
    - run: ./macOS-local-init
    - run: ./macOS-local-run-backend
    - run: ./macOS-local-run-frontend
