name: ubuntu

on:
  push:
    branches: [ local ]
  workflow_dispatch:

permissions:
  contents: read

env:
  BEE_MAIN_PORT: 8081
  BEE_MONITOR_PORT: 8080
  BEE_URL_DEV: "http://localhost:$BEE_MAIN_PORT"
  BEE_URL_LOCAL: "http://bee.peacetrue.local"
  BEE_URL_PROD: "http://bee.peacetrue.cn"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
#    - run: sudo apt install nginx-core -y
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - run: ./set-env
    - run: ./ubuntu-dev-run-backend
    - run: ./ubuntu-dev-init
    - run: ./ubuntu-dev-run-frontend
