name: ubuntu

on:
  push:
    branches: [ local ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - run: ./set-env
    - run: ./ubuntu-dev-init
    - run: ./ubuntu-dev-run-backend
    - run: ./ubuntu-dev-run-frontend
